### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by THEGOLDENPRO** [THEGOLDENPRO/snakelings#10]
Here's an always updating list of exercises and features we must implement to get this project cooking.

> [!NOTE]
> This issue is always being updated and added upon, so these tasks don't indicate the completeness of this project.

## Features
- [x] Print markdown to terminal.
- [x] Pytest integration (some exercises will make use of pytest to test the answers/values)
- [x] Command to update exercises folder with new exercises.

## Exercises to implement.
This list is heavily inspired by Rustlings, in fact most of [the exercises are basically from Rustlings](https://github.com/rust-lang/rustlings/tree/main/exercises).

Whatever is in brackets are notes. If you see the letter "E", it is referring to "Exercise" so whatever number comes after that is the exercise id we are referring to.

- [x] Fix this print statement. (after E1)
- [ ] Print "Hello, World!" from scratch. (no prior code given, should be after [E1](https://github.com/THEGOLDENPRO/snekilings/tree/76caef1956fe69c0fb2ded94aedb73a9923587f5/snekilings/exercises/1_hello_world))
- [ ] Assign a string with the value "Hello" to this variable. (below the variable should be printed with a random name, should be after [E3](https://github.com/THEGOLDENPRO/snekilings/tree/76caef1956fe69c0fb2ded94aedb73a9923587f5/snekilings/exercises/3_assign_variable_wo_equal))
- [ ] Change this number into a string. (after [E4](https://github.com/THEGOLDENPRO/snekilings/tree/76caef1956fe69c0fb2ded94aedb73a9923587f5/snekilings/exercises/4_basic_math))
